; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Dec 16 2020 16:32:24 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATA7EBBRGP6X1:
	dc.w DATA7EBBRGP6X1_0-DATA7EBBRGP6X1, DATA7EBBRGP6X1_1-DATA7EBBRGP6X1
	dc.w DATA7EBBRGP6X1_2-DATA7EBBRGP6X1, DATA7EBBRGP6X1_3-DATA7EBBRGP6X1
	dc.w DATA7EBBRGP6X1_4-DATA7EBBRGP6X1, DATA7EBBRGP6X1_5-DATA7EBBRGP6X1
	dc.w DATA7EBBRGP6X1_6-DATA7EBBRGP6X1, DATA7EBBRGP6X1_7-DATA7EBBRGP6X1
	dc.w DATA7EBBRGP6X1_8-DATA7EBBRGP6X1, DATA7EBBRGP6X1_9-DATA7EBBRGP6X1
	dc.w DATA7EBBRGP6X1_A-DATA7EBBRGP6X1
DATA7EBBRGP6X1_0: dc.b $3
	dc.b $FC, $0, $0, $8F, $E8
	dc.b $E8, $E, $0, $0, $F0
	dc.b $0, $F, $0, $6F, $F0
DATA7EBBRGP6X1_1: dc.b $4
	dc.b $E8, $D, $0, $E, $F0
	dc.b $E8, $E, $0, $0, $F0
	dc.b $0, $F, $0, $6F, $F0
	dc.b $FC, $0, $0, $8F, $E8
DATA7EBBRGP6X1_2: dc.b $4
	dc.b $E9, $D, $0, $E, $F0
	dc.b $E9, $E, $0, $0, $F0
	dc.b $1, $F, $0, $7F, $F0
	dc.b $FD, $0, $0, $8F, $E8
DATA7EBBRGP6X1_3: dc.b $4
	dc.b $F4, $F, $8, $20, $F0
	dc.b $F5, $4, $8, $30, $10
	dc.b $8, $9, $8, $4E, $F0
	dc.b $EC, $E, $0, $0, $F0
DATA7EBBRGP6X1_4: dc.b $4
	dc.b $F0, $F, $8, $20, $F0
	dc.b $F1, $4, $8, $30, $10
	dc.b $8, $6, $8, $3E, $F8
	dc.b $E8, $E, $0, $0, $F0
DATA7EBBRGP6X1_5: dc.b $4
	dc.b $E8, $D, $0, $16, $EC
	dc.b $E8, $1, $0, $1E, $C
	dc.b $E8, $E, $0, $0, $F0
	dc.b $0, $F, $0, $6F, $F0
DATA7EBBRGP6X1_6: dc.b $7
	dc.b $E8, $D, $0, $16, $EC
	dc.b $E8, $1, $0, $1E, $C
	dc.b $4, $9, $8, $34, $0
	dc.b $4, $5, $8, $3A, $E8
	dc.b $F0, $F, $8, $20, $F0
	dc.b $F1, $4, $8, $54, $10
	dc.b $F1, $4, $0, $54, $E0
DATA7EBBRGP6X1_7: dc.b $5
	dc.b $F0, $F, $8, $20, $F0
	dc.b $F1, $4, $8, $30, $10
	dc.b $4, $9, $8, $34, $0
	dc.b $4, $5, $8, $3A, $E8
	dc.b $E8, $E, $0, $0, $F0
DATA7EBBRGP6X1_8: dc.b $6
	dc.b $EE, $F, $8, $20, $F0
	dc.b $EF, $4, $8, $30, $10
	dc.b $9, $5, $8, $44, $0
	dc.b $3, $1, $8, $48, $F8
	dc.b $B, $5, $8, $4A, $E8
	dc.b $E6, $E, $0, $0, $F0
DATA7EBBRGP6X1_9: dc.b $8
	dc.b $E8, $D, $0, $16, $EC
	dc.b $E8, $1, $0, $1E, $C
	dc.b $E8, $E, $0, $0, $F0
	dc.b $0, $F, $0, $6F, $F0
	dc.b $E0, $D, $3E, $F0, $F0
	dc.b $F0, $D, $3E, $F0, $F0
	dc.b $0, $D, $3E, $F0, $F0
	dc.b $10, $D, $3E, $F0, $F0
DATA7EBBRGP6X1_A: dc.b $3
	dc.b $EC, $D, $0, $56, $E4
	dc.b $F4, $8, $0, $5E, $4
	dc.b $EC, $D, $0, $61, $FC
	even