; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Dec 16 2020 16:28:54 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATAN3VKMMH6XF:
	dc.w DATAN3VKMMH6XF_0-DATAN3VKMMH6XF, DATAN3VKMMH6XF_1-DATAN3VKMMH6XF
	dc.w DATAN3VKMMH6XF_2-DATAN3VKMMH6XF, DATAN3VKMMH6XF_3-DATAN3VKMMH6XF
	dc.w DATAN3VKMMH6XF_4-DATAN3VKMMH6XF, DATAN3VKMMH6XF_5-DATAN3VKMMH6XF
	dc.w DATAN3VKMMH6XF_6-DATAN3VKMMH6XF, DATAN3VKMMH6XF_7-DATAN3VKMMH6XF
	dc.w DATAN3VKMMH6XF_8-DATAN3VKMMH6XF, DATAN3VKMMH6XF_9-DATAN3VKMMH6XF
	dc.w DATAN3VKMMH6XF_A-DATAN3VKMMH6XF, DATAN3VKMMH6XF_B-DATAN3VKMMH6XF
	dc.w DATAN3VKMMH6XF_C-DATAN3VKMMH6XF
DATAN3VKMMH6XF_0: dc.b $6
	dc.b $EC, $1, $0, $A, $E4
	dc.b $EC, $5, $0, $C, $C
	dc.b $FC, $E, $20, $10, $E4
	dc.b $FC, $E, $20, $1C, $4
	dc.b $14, $C, $20, $28, $EC
	dc.b $14, $0, $20, $2C, $C
DATAN3VKMMH6XF_1: dc.b $2
	dc.b $E4, $4, $0, $0, $F4
	dc.b $EC, $D, $0, $2, $EC
DATAN3VKMMH6XF_2: dc.b $2
	dc.b $E4, $4, $0, $0, $F4
	dc.b $EC, $D, $0, $35, $EC
DATAN3VKMMH6XF_3: dc.b $3
	dc.b $E4, $8, $0, $3D, $F4
	dc.b $EC, $9, $0, $40, $EC
	dc.b $EC, $5, $0, $46, $4
DATAN3VKMMH6XF_4: dc.b $3
	dc.b $E4, $8, $0, $4A, $F4
	dc.b $EC, $9, $0, $4D, $EC
	dc.b $EC, $5, $0, $53, $4
DATAN3VKMMH6XF_5: dc.b $3
	dc.b $E4, $8, $0, $57, $F4
	dc.b $EC, $9, $0, $5A, $EC
	dc.b $EC, $5, $0, $60, $4
DATAN3VKMMH6XF_6: dc.b $3
	dc.b $E4, $4, $0, $64, $4
	dc.b $E4, $4, $0, $0, $F4
	dc.b $EC, $D, $0, $35, $EC
DATAN3VKMMH6XF_7: dc.b $4
	dc.b $E4, $9, $0, $66, $F4
	dc.b $E4, $8, $0, $57, $F4
	dc.b $EC, $9, $0, $5A, $EC
	dc.b $EC, $5, $0, $60, $4
DATAN3VKMMH6XF_8: dc.b $1
	dc.b $4, $5, $0, $2D, $22
DATAN3VKMMH6XF_9: dc.b $1
	dc.b $4, $5, $0, $31, $22
DATAN3VKMMH6XF_A: dc.b $0
DATAN3VKMMH6XF_B: dc.b $2
	dc.b $0, $8, $1, $2A, $22
	dc.b $8, $8, $11, $2A, $22
DATAN3VKMMH6XF_C: dc.b $2
	dc.b $F8, $B, $1, $2D, $22
	dc.b $0, $1, $1, $39, $3A
	even