; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Dec 16 2020 16:33:58 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATASGJJV5BB4EH:
	dc.w DATASGJJV5BB4EH_0-DATASGJJV5BB4EH, DATASGJJV5BB4EH_1-DATASGJJV5BB4EH
DATASGJJV5BB4EH_0: dc.b $6
	dc.b $E4, $8, $0, $20, $F4
	dc.b $EC, $D, $0, $23, $E4
	dc.b $EC, $9, $0, $2B, $4
	dc.b $FC, $5, $20, $3A, $E4
	dc.b $FC, $E, $20, $3E, $4
	dc.b $14, $4, $20, $4A, $4
DATASGJJV5BB4EH_1: dc.b $6
	dc.b $E4, $A, $0, $31, $F4
	dc.b $EC, $5, $0, $23, $E4
	dc.b $EC, $9, $0, $2B, $4
	dc.b $FC, $5, $20, $3A, $E4
	dc.b $FC, $E, $20, $3E, $4
	dc.b $14, $4, $20, $4A, $4
	even