; ================================================================================
; Sprite Mappings - generated by Flex 2 Mon Jan 04 2021 11:38:11 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATAKF9S0D38XBL:
	dc.w DATAKF9S0D38XBL_0-DATAKF9S0D38XBL, DATAKF9S0D38XBL_1-DATAKF9S0D38XBL
	dc.w DATAKF9S0D38XBL_2-DATAKF9S0D38XBL, DATAKF9S0D38XBL_3-DATAKF9S0D38XBL
	dc.w DATAKF9S0D38XBL_4-DATAKF9S0D38XBL
DATAKF9S0D38XBL_0: dc.b $3
	dc.b $F0, $B, $0, $0, $E8
	dc.b $F0, $B, $8, $0, $0
	dc.b $10, $1, $0, $38, $FC
DATAKF9S0D38XBL_1: dc.b $2
	dc.b $F0, $F, $0, $C, $F0
	dc.b $10, $1, $0, $38, $FC
DATAKF9S0D38XBL_2: dc.b $2
	dc.b $F0, $3, $0, $1C, $FC
	dc.b $10, $1, $8, $38, $FC
DATAKF9S0D38XBL_3: dc.b $2
	dc.b $F0, $F, $8, $C, $F0
	dc.b $10, $1, $8, $38, $FC
DATAKF9S0D38XBL_4: dc.b $3
	dc.b $F0, $B, $0, $20, $E8
	dc.b $F0, $B, $0, $2C, $0
	dc.b $10, $1, $0, $38, $FC
	even