; ================================================================================
; Sprite Mappings - generated by Flex 2 Sun Apr 24 2022 16:33:30 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAF4PCTJKUZ3Q:
	dc.w $0, DATAF4PCTJKUZ3Q_1-DATAF4PCTJKUZ3Q
	dc.w DATAF4PCTJKUZ3Q_2-DATAF4PCTJKUZ3Q, DATAF4PCTJKUZ3Q_3-DATAF4PCTJKUZ3Q
	dc.w DATAF4PCTJKUZ3Q_4-DATAF4PCTJKUZ3Q, DATAF4PCTJKUZ3Q_5-DATAF4PCTJKUZ3Q
	dc.w DATAF4PCTJKUZ3Q_6-DATAF4PCTJKUZ3Q, DATAF4PCTJKUZ3Q_7-DATAF4PCTJKUZ3Q
	dc.w DATAF4PCTJKUZ3Q_8-DATAF4PCTJKUZ3Q, DATAF4PCTJKUZ3Q_9-DATAF4PCTJKUZ3Q
	dc.w DATAF4PCTJKUZ3Q_A-DATAF4PCTJKUZ3Q, DATAF4PCTJKUZ3Q_B-DATAF4PCTJKUZ3Q
	dc.w DATAF4PCTJKUZ3Q_C-DATAF4PCTJKUZ3Q, DATAF4PCTJKUZ3Q_D-DATAF4PCTJKUZ3Q
	dc.w DATAF4PCTJKUZ3Q_E-DATAF4PCTJKUZ3Q, DATAF4PCTJKUZ3Q_F-DATAF4PCTJKUZ3Q
	dc.w DATAF4PCTJKUZ3Q_10-DATAF4PCTJKUZ3Q, DATAF4PCTJKUZ3Q_11-DATAF4PCTJKUZ3Q
	dc.w DATAF4PCTJKUZ3Q_12-DATAF4PCTJKUZ3Q, DATAF4PCTJKUZ3Q_13-DATAF4PCTJKUZ3Q
	dc.w DATAF4PCTJKUZ3Q_14-DATAF4PCTJKUZ3Q, DATAF4PCTJKUZ3Q_15-DATAF4PCTJKUZ3Q
	dc.w DATAF4PCTJKUZ3Q_16-DATAF4PCTJKUZ3Q, DATAF4PCTJKUZ3Q_17-DATAF4PCTJKUZ3Q
	dc.w DATAF4PCTJKUZ3Q_18-DATAF4PCTJKUZ3Q, DATAF4PCTJKUZ3Q_19-DATAF4PCTJKUZ3Q
	dc.w DATAF4PCTJKUZ3Q_1A-DATAF4PCTJKUZ3Q, DATAF4PCTJKUZ3Q_1B-DATAF4PCTJKUZ3Q
	dc.w DATAF4PCTJKUZ3Q_1C-DATAF4PCTJKUZ3Q, DATAF4PCTJKUZ3Q_1D-DATAF4PCTJKUZ3Q
	dc.w DATAF4PCTJKUZ3Q_1E-DATAF4PCTJKUZ3Q, DATAF4PCTJKUZ3Q_1F-DATAF4PCTJKUZ3Q
	dc.w DATAF4PCTJKUZ3Q_20-DATAF4PCTJKUZ3Q, DATAF4PCTJKUZ3Q_21-DATAF4PCTJKUZ3Q
	dc.w DATAF4PCTJKUZ3Q_22-DATAF4PCTJKUZ3Q, DATAF4PCTJKUZ3Q_23-DATAF4PCTJKUZ3Q
	dc.w DATAF4PCTJKUZ3Q_24-DATAF4PCTJKUZ3Q, DATAF4PCTJKUZ3Q_25-DATAF4PCTJKUZ3Q
	dc.w DATAF4PCTJKUZ3Q_26-DATAF4PCTJKUZ3Q, DATAF4PCTJKUZ3Q_27-DATAF4PCTJKUZ3Q
	dc.w DATAF4PCTJKUZ3Q_28-DATAF4PCTJKUZ3Q, DATAF4PCTJKUZ3Q_29-DATAF4PCTJKUZ3Q
	dc.w DATAF4PCTJKUZ3Q_2A-DATAF4PCTJKUZ3Q, DATAF4PCTJKUZ3Q_2B-DATAF4PCTJKUZ3Q
	dc.w DATAF4PCTJKUZ3Q_2C-DATAF4PCTJKUZ3Q, DATAF4PCTJKUZ3Q_2D-DATAF4PCTJKUZ3Q
	dc.w DATAF4PCTJKUZ3Q_2E-DATAF4PCTJKUZ3Q, DATAF4PCTJKUZ3Q_2F-DATAF4PCTJKUZ3Q
	dc.w DATAF4PCTJKUZ3Q_30-DATAF4PCTJKUZ3Q, DATAF4PCTJKUZ3Q_31-DATAF4PCTJKUZ3Q
	dc.w DATAF4PCTJKUZ3Q_32-DATAF4PCTJKUZ3Q, DATAF4PCTJKUZ3Q_33-DATAF4PCTJKUZ3Q
	dc.w DATAF4PCTJKUZ3Q_34-DATAF4PCTJKUZ3Q, DATAF4PCTJKUZ3Q_35-DATAF4PCTJKUZ3Q
	dc.w DATAF4PCTJKUZ3Q_36-DATAF4PCTJKUZ3Q, DATAF4PCTJKUZ3Q_37-DATAF4PCTJKUZ3Q
	dc.w DATAF4PCTJKUZ3Q_38-DATAF4PCTJKUZ3Q, DATAF4PCTJKUZ3Q_39-DATAF4PCTJKUZ3Q
	dc.w DATAF4PCTJKUZ3Q_3A-DATAF4PCTJKUZ3Q, DATAF4PCTJKUZ3Q_3B-DATAF4PCTJKUZ3Q
	dc.w DATAF4PCTJKUZ3Q_3C-DATAF4PCTJKUZ3Q, DATAF4PCTJKUZ3Q_3D-DATAF4PCTJKUZ3Q
	dc.w DATAF4PCTJKUZ3Q_3E-DATAF4PCTJKUZ3Q, DATAF4PCTJKUZ3Q_3F-DATAF4PCTJKUZ3Q
	dc.w DATAF4PCTJKUZ3Q_40-DATAF4PCTJKUZ3Q, DATAF4PCTJKUZ3Q_41-DATAF4PCTJKUZ3Q
	dc.w DATAF4PCTJKUZ3Q_42-DATAF4PCTJKUZ3Q, DATAF4PCTJKUZ3Q_43-DATAF4PCTJKUZ3Q
	dc.w DATAF4PCTJKUZ3Q_44-DATAF4PCTJKUZ3Q, DATAF4PCTJKUZ3Q_45-DATAF4PCTJKUZ3Q
	dc.w DATAF4PCTJKUZ3Q_46-DATAF4PCTJKUZ3Q, DATAF4PCTJKUZ3Q_47-DATAF4PCTJKUZ3Q
	dc.w DATAF4PCTJKUZ3Q_48-DATAF4PCTJKUZ3Q, DATAF4PCTJKUZ3Q_49-DATAF4PCTJKUZ3Q
	dc.w DATAF4PCTJKUZ3Q_4A-DATAF4PCTJKUZ3Q, DATAF4PCTJKUZ3Q_4B-DATAF4PCTJKUZ3Q
	dc.w DATAF4PCTJKUZ3Q_4C-DATAF4PCTJKUZ3Q, DATAF4PCTJKUZ3Q_4D-DATAF4PCTJKUZ3Q
	dc.w DATAF4PCTJKUZ3Q_4E-DATAF4PCTJKUZ3Q, DATAF4PCTJKUZ3Q_4F-DATAF4PCTJKUZ3Q
	dc.w DATAF4PCTJKUZ3Q_50-DATAF4PCTJKUZ3Q, DATAF4PCTJKUZ3Q_51-DATAF4PCTJKUZ3Q
	dc.w DATAF4PCTJKUZ3Q_52-DATAF4PCTJKUZ3Q, DATAF4PCTJKUZ3Q_53-DATAF4PCTJKUZ3Q
	dc.w DATAF4PCTJKUZ3Q_54-DATAF4PCTJKUZ3Q, DATAF4PCTJKUZ3Q_55-DATAF4PCTJKUZ3Q
	dc.w DATAF4PCTJKUZ3Q_56-DATAF4PCTJKUZ3Q, DATAF4PCTJKUZ3Q_57-DATAF4PCTJKUZ3Q
DATAF4PCTJKUZ3Q_1: dc.b $4
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $D, $0, $3, $F0
	dc.b $4, $8, $0, $B, $F0
	dc.b $C, $8, $0, $E, $F8
DATAF4PCTJKUZ3Q_2: dc.b $3
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $9, $0, $6, $F0
	dc.b $C, $8, $0, $C, $F8
DATAF4PCTJKUZ3Q_3: dc.b $3
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $9, $0, $6, $F0
	dc.b $C, $8, $0, $C, $F8
DATAF4PCTJKUZ3Q_4: dc.b $3
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $9, $0, $6, $F0
	dc.b $C, $8, $0, $C, $F8
DATAF4PCTJKUZ3Q_5: dc.b $3
	dc.b $EC, $A, $0, $0, $EC
	dc.b $4, $9, $0, $9, $FC
	dc.b $F4, $1, $0, $F, $4
DATAF4PCTJKUZ3Q_6: dc.b $4
	dc.b $EB, $D, $0, $0, $EC
	dc.b $FB, $9, $0, $8, $EC
	dc.b $FB, $6, $0, $E, $4
	dc.b $B, $4, $0, $14, $EC
DATAF4PCTJKUZ3Q_7: dc.b $2
	dc.b $EC, $D, $0, $0, $ED
	dc.b $FC, $E, $0, $8, $F5
DATAF4PCTJKUZ3Q_8: dc.b $2
	dc.b $ED, $9, $0, $0, $F3
	dc.b $FD, $A, $0, $6, $F3
DATAF4PCTJKUZ3Q_9: dc.b $4
	dc.b $EB, $9, $0, $0, $F4
	dc.b $FB, $9, $0, $6, $EC
	dc.b $FB, $6, $0, $C, $4
	dc.b $B, $4, $0, $12, $EC
DATAF4PCTJKUZ3Q_A: dc.b $2
	dc.b $EC, $9, $0, $0, $F3
	dc.b $FC, $E, $0, $6, $EB
DATAF4PCTJKUZ3Q_B: dc.b $3
	dc.b $ED, $D, $0, $0, $EC
	dc.b $FD, $C, $0, $8, $F4
	dc.b $5, $9, $0, $C, $F4
DATAF4PCTJKUZ3Q_C: dc.b $5
	dc.b $EB, $9, $0, $0, $EB
	dc.b $EB, $6, $0, $6, $3
	dc.b $FB, $8, $0, $C, $EB
	dc.b $3, $9, $0, $F, $F3
	dc.b $13, $0, $0, $15, $FB
DATAF4PCTJKUZ3Q_D: dc.b $6
	dc.b $EC, $9, $0, $0, $EC
	dc.b $EC, $1, $0, $6, $4
	dc.b $FC, $C, $0, $8, $EC
	dc.b $4, $9, $0, $C, $F4
	dc.b $FC, $5, $0, $12, $C
	dc.b $F4, $0, $0, $16, $14
DATAF4PCTJKUZ3Q_E: dc.b $4
	dc.b $ED, $9, $0, $0, $ED
	dc.b $ED, $1, $0, $6, $5
	dc.b $FD, $D, $0, $8, $F5
	dc.b $D, $8, $0, $10, $FD
DATAF4PCTJKUZ3Q_F: dc.b $5
	dc.b $EB, $9, $0, $0, $EB
	dc.b $EB, $5, $0, $6, $3
	dc.b $FB, $D, $0, $A, $F3
	dc.b $B, $8, $0, $12, $F3
	dc.b $13, $4, $0, $15, $FB
DATAF4PCTJKUZ3Q_10: dc.b $4
	dc.b $EC, $9, $0, $0, $EC
	dc.b $EC, $1, $0, $6, $4
	dc.b $FC, $D, $0, $8, $F4
	dc.b $C, $8, $0, $10, $FC
DATAF4PCTJKUZ3Q_11: dc.b $5
	dc.b $ED, $9, $0, $0, $ED
	dc.b $ED, $1, $0, $6, $5
	dc.b $FD, $0, $0, $8, $ED
	dc.b $FD, $D, $0, $9, $F5
	dc.b $D, $8, $0, $11, $FD
DATAF4PCTJKUZ3Q_12: dc.b $4
	dc.b $F4, $7, $0, $0, $EB
	dc.b $EC, $9, $0, $8, $FB
	dc.b $FC, $4, $0, $E, $FB
	dc.b $4, $9, $0, $10, $FB
DATAF4PCTJKUZ3Q_13: dc.b $2
	dc.b $F4, $7, $0, $0, $EC
	dc.b $EC, $B, $0, $8, $FC
DATAF4PCTJKUZ3Q_14: dc.b $2
	dc.b $F4, $6, $0, $0, $ED
	dc.b $F4, $A, $0, $6, $FD
DATAF4PCTJKUZ3Q_15: dc.b $4
	dc.b $F4, $6, $0, $0, $EB
	dc.b $EC, $9, $0, $6, $FB
	dc.b $FC, $4, $0, $C, $FB
	dc.b $4, $9, $0, $E, $FB
DATAF4PCTJKUZ3Q_16: dc.b $2
	dc.b $F4, $6, $0, $0, $EC
	dc.b $F4, $B, $0, $6, $FC
DATAF4PCTJKUZ3Q_17: dc.b $3
	dc.b $F4, $7, $0, $0, $ED
	dc.b $EC, $0, $0, $8, $FD
	dc.b $F4, $A, $0, $9, $FD
DATAF4PCTJKUZ3Q_18: dc.b $6
	dc.b $FD, $6, $0, $0, $EB
	dc.b $ED, $4, $0, $6, $F3
	dc.b $F5, $4, $0, $8, $EB
	dc.b $F5, $A, $0, $A, $FB
	dc.b $D, $0, $0, $13, $FB
	dc.b $FD, $0, $0, $14, $13
DATAF4PCTJKUZ3Q_19: dc.b $6
	dc.b $FC, $6, $0, $0, $EC
	dc.b $E4, $8, $0, $6, $F4
	dc.b $EC, $4, $0, $9, $FC
	dc.b $F4, $4, $0, $B, $EC
	dc.b $F4, $A, $0, $D, $FC
	dc.b $C, $0, $0, $16, $FC
DATAF4PCTJKUZ3Q_1A: dc.b $4
	dc.b $FB, $6, $0, $0, $ED
	dc.b $F3, $4, $0, $6, $ED
	dc.b $EB, $A, $0, $8, $FD
	dc.b $3, $4, $0, $11, $FD
DATAF4PCTJKUZ3Q_1B: dc.b $5
	dc.b $FD, $6, $0, $0, $EB
	dc.b $ED, $8, $0, $6, $F3
	dc.b $F5, $4, $0, $9, $EB
	dc.b $F5, $D, $0, $B, $FB
	dc.b $5, $8, $0, $13, $FB
DATAF4PCTJKUZ3Q_1C: dc.b $4
	dc.b $FC, $6, $0, $0, $EC
	dc.b $F4, $4, $0, $6, $EC
	dc.b $EC, $A, $0, $8, $FC
	dc.b $4, $4, $0, $11, $FC
DATAF4PCTJKUZ3Q_1D: dc.b $5
	dc.b $FB, $6, $0, $0, $ED
	dc.b $EB, $A, $0, $6, $FD
	dc.b $F3, $4, $0, $F, $ED
	dc.b $3, $4, $0, $11, $FD
	dc.b $B, $0, $0, $13, $FD
DATAF4PCTJKUZ3Q_1E: dc.b $2
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
DATAF4PCTJKUZ3Q_1F: dc.b $2
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
DATAF4PCTJKUZ3Q_20: dc.b $2
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
DATAF4PCTJKUZ3Q_21: dc.b $2
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
DATAF4PCTJKUZ3Q_22: dc.b $4
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
	dc.b $FE, $0, $0, $14, $EE
DATAF4PCTJKUZ3Q_23: dc.b $3
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
DATAF4PCTJKUZ3Q_24: dc.b $4
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
	dc.b $FE, $0, $0, $14, $EE
DATAF4PCTJKUZ3Q_25: dc.b $3
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
DATAF4PCTJKUZ3Q_26: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
DATAF4PCTJKUZ3Q_27: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
DATAF4PCTJKUZ3Q_28: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
DATAF4PCTJKUZ3Q_29: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
DATAF4PCTJKUZ3Q_2A: dc.b $4
	dc.b $FA, $6, $0, $0, $EE
	dc.b $F2, $4, $0, $6, $EE
	dc.b $EA, $B, $0, $8, $FE
	dc.b $A, $0, $0, $14, $FE
DATAF4PCTJKUZ3Q_2B: dc.b $2
	dc.b $F2, $7, $0, $0, $EE
	dc.b $EA, $B, $0, $8, $FE
DATAF4PCTJKUZ3Q_2C: dc.b $4
	dc.b $FA, $6, $0, $0, $EE
	dc.b $F2, $4, $0, $6, $EE
	dc.b $EA, $B, $0, $8, $FE
	dc.b $A, $0, $0, $14, $FE
DATAF4PCTJKUZ3Q_2D: dc.b $2
	dc.b $F2, $7, $0, $0, $EE
	dc.b $EA, $B, $0, $8, $FE
DATAF4PCTJKUZ3Q_2E: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAF4PCTJKUZ3Q_2F: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAF4PCTJKUZ3Q_30: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAF4PCTJKUZ3Q_31: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAF4PCTJKUZ3Q_32: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAF4PCTJKUZ3Q_33: dc.b $2
	dc.b $F4, $E, $0, $0, $EC
	dc.b $F4, $2, $0, $C, $C
DATAF4PCTJKUZ3Q_34: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAF4PCTJKUZ3Q_35: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATAF4PCTJKUZ3Q_36: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAF4PCTJKUZ3Q_37: dc.b $2
	dc.b $ED, $9, $0, $0, $F0
	dc.b $FD, $E, $0, $6, $F0
DATAF4PCTJKUZ3Q_38: dc.b $4
	dc.b $ED, $9, $0, $0, $F0
	dc.b $FD, $D, $0, $6, $F0
	dc.b $D, $4, $0, $E, $0
	dc.b $5, $0, $0, $10, $E8
DATAF4PCTJKUZ3Q_39: dc.b $3
	dc.b $5, $A, $0, $0, $EC
	dc.b $F5, $9, $0, $9, $FC
	dc.b $5, $4, $0, $F, $4
DATAF4PCTJKUZ3Q_3A: dc.b $3
	dc.b $EC, $8, $8, $0, $E8
	dc.b $F4, $2, $8, $3, $0
	dc.b $F4, $F, $8, $6, $E0
DATAF4PCTJKUZ3Q_3B: dc.b $3
	dc.b $EC, $E, $8, $0, $E8
	dc.b $4, $D, $8, $C, $E0
	dc.b $C, $0, $18, $14, $0
DATAF4PCTJKUZ3Q_3C: dc.b $3
	dc.b $F4, $D, $0, $0, $FC
	dc.b $FC, $5, $0, $8, $EC
	dc.b $4, $8, $0, $C, $FC
DATAF4PCTJKUZ3Q_3D: dc.b $2
	dc.b $F4, $A, $0, $0, $E8
	dc.b $F4, $A, $8, $0, $0
DATAF4PCTJKUZ3Q_3E: dc.b $3
	dc.b $F4, $D, $0, $0, $E4
	dc.b $FC, $0, $0, $8, $4
	dc.b $4, $C, $0, $9, $EC
DATAF4PCTJKUZ3Q_3F: dc.b $3
	dc.b $F4, $D, $0, $0, $FC
	dc.b $FC, $5, $0, $8, $EC
	dc.b $4, $8, $0, $C, $FC
DATAF4PCTJKUZ3Q_40: dc.b $3
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $4, $0, $C, $F8
	dc.b $10, $0, $0, $E, $F8
DATAF4PCTJKUZ3Q_41: dc.b $4
	dc.b $F8, $E, $0, $0, $E8
	dc.b $0, $5, $0, $C, $8
	dc.b $F8, $0, $0, $10, $8
	dc.b $F0, $0, $0, $11, $F8
DATAF4PCTJKUZ3Q_42: dc.b $4
	dc.b $F8, $E, $0, $0, $E8
	dc.b $0, $5, $0, $C, $8
	dc.b $F8, $0, $0, $10, $8
	dc.b $F0, $0, $0, $11, $F8
DATAF4PCTJKUZ3Q_43: dc.b $5
	dc.b $E8, $A, $0, $0, $F4
	dc.b $F0, $1, $0, $9, $C
	dc.b $0, $9, $0, $B, $F4
	dc.b $10, $4, $0, $11, $F4
	dc.b $0, $0, $0, $13, $EC
DATAF4PCTJKUZ3Q_44: dc.b $5
	dc.b $E8, $A, $0, $0, $F4
	dc.b $E8, $1, $0, $9, $C
	dc.b $0, $9, $0, $B, $F4
	dc.b $10, $4, $0, $11, $F4
	dc.b $0, $0, $0, $13, $EC
DATAF4PCTJKUZ3Q_45: dc.b $2
	dc.b $ED, $A, $0, $0, $F3
	dc.b $5, $D, $0, $9, $EB
DATAF4PCTJKUZ3Q_46: dc.b $3
	dc.b $EC, $A, $0, $0, $F3
	dc.b $4, $8, $0, $9, $F3
	dc.b $C, $4, $0, $C, $F3
DATAF4PCTJKUZ3Q_47: dc.b $2
	dc.b $ED, $A, $0, $0, $F3
	dc.b $5, $D, $0, $9, $EB
DATAF4PCTJKUZ3Q_48: dc.b $3
	dc.b $EC, $A, $0, $0, $F3
	dc.b $4, $8, $0, $9, $F3
	dc.b $C, $4, $0, $C, $F3
DATAF4PCTJKUZ3Q_49: dc.b $2
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $E, $0, $6, $F0
DATAF4PCTJKUZ3Q_4A: dc.b $3
	dc.b $EC, $A, $0, $0, $F0
	dc.b $4, $5, $0, $9, $F8
	dc.b $E4, $0, $0, $D, $F8
DATAF4PCTJKUZ3Q_4B: dc.b $3
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $B, $0, $A, $F4
DATAF4PCTJKUZ3Q_4C: dc.b $5
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $8, $C, $0, $10, $F4
	dc.b $10, $0, $0, $14, $F4
DATAF4PCTJKUZ3Q_4D: dc.b $5
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $8, $C, $0, $10, $F4
	dc.b $10, $0, $0, $14, $F4
DATAF4PCTJKUZ3Q_4E: dc.b $2
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $F, $0, $3, $F0
DATAF4PCTJKUZ3Q_4F: dc.b $3
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $E, $0, $3, $F0
	dc.b $C, $8, $0, $F, $F8
DATAF4PCTJKUZ3Q_50: dc.b $1
	dc.b $F0, $B, $0, $0, $F4
DATAF4PCTJKUZ3Q_51: dc.b $1
	dc.b $F4, $6, $0, $0, $F8
DATAF4PCTJKUZ3Q_52: dc.b $1
	dc.b $F8, $1, $0, $0, $FC
DATAF4PCTJKUZ3Q_53: dc.b $3
	dc.b $F4, $D, $8, $0, $E4
	dc.b $FC, $5, $8, $8, $4
	dc.b $4, $8, $8, $C, $EC
DATAF4PCTJKUZ3Q_54: dc.b $3
	dc.b $F4, $D, $8, $0, $FC
	dc.b $FC, $0, $8, $8, $F4
	dc.b $4, $C, $8, $9, $F4
DATAF4PCTJKUZ3Q_55: dc.b $3
	dc.b $F0, $E, $0, $0, $EC
	dc.b $F8, $1, $0, $C, $C
	dc.b $8, $C, $0, $E, $F4
DATAF4PCTJKUZ3Q_56: dc.b $3
	dc.b $EB, $9, $0, $0, $F4
	dc.b $FB, $E, $0, $6, $EC
	dc.b $3, $1, $0, $12, $C
DATAF4PCTJKUZ3Q_57: dc.b $2
	dc.b $F0, $F, $0, $0, $EC
	dc.b $F8, $2, $0, $10, $C
	even